### ISSUE TITLE
[oh-my-zsh] theme 'daivasmara' not found error

### ISSUE THREAD

**Issue by piotrdylag** [Daivasmara/daivasmara.zsh-theme#2]
Hi,

when I copied entire folder .zsh-theme in to theme folder, I changed theme name in .zshc and reload it. But I got error: [oh-my-zsh] theme 'daivasmara' not found
Can you help?

**Comment by Daivasmara** [comment]
Hello,

I think all you need to copy is the `.zsh-theme` file into the `~/.oh-my-zsh/theme` folder, then set `ZSH_THEME=daivasmara` in the `.zshrc`
